### ISSUE TITLE
README could use an example of how to install and run this tool

### ISSUE THREAD

**Issue by yurishkuro** [sectioneight/md-to-godoc#1]
Also, I wonder if it's possible to put it as go:generate directive in the `doc.go` files themselves so that it's easy to regenerate across the repo when README files change.

**Comment by yurishkuro** [comment]
@sectioneight meanwhile, I gave it a try: https://github.com/uber/jaeger/pull/3

**Comment by ascandella** [comment]
Yea, we have some `make` rules in UberFx -- `go generate` is an interesting idea

**Comment by yurishkuro** [comment]
I used go:generate, followed by updateLiceses, but had to put the directives into another file `md2doc.go`

**Comment by ascandella** [comment]
Cool. FYI the latest version uses // comments to be a bit more idiomatic.
