### ISSUE TITLE
Typo in the name of license file

### ISSUE THREAD

**Issue by yurishkuro** [sectioneight/md-to-godoc#2]

**Comment by ascandella** [comment]
orly?

**Comment by yurishkuro** [comment]
s/LICENCE/LICENSE/

**Comment by ascandella** [comment]
hmm. @lupie we decided on one. which one is right?

**Comment by ascandella** [comment]
ah yes, you are write. thanks @yurishkuro

**Comment by Lupie** [comment]
Thank you, @sectioneight and @yurishkuro. This is good.
Had my GitHub notifications set badly. Should be more responsive now.
